version: "3.8"
services:
  jenkins:
    container_name: jenkins
    build:
      context: ../lab05-jenkins-docker/jenkins
    image: jenkins/docker
    ports:
      - 8080:8080
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net   
  sonarqube:
      image: sonarqube:8.6.1-developer
      container_name: sonarqube
      ports:
        - 8081:9000
      networks:
        - net
      ulimits:
        nofile:
          soft: 65536
          hard: 65536
      # volumes:
      #   - sonarqube_conf:/opt/sonarqube/conf
      #   - sonarqube_data:/opt/sonarqube/data
      #   - sonarqube_extensions:/opt/sonarqube/extensions
      #   - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins              
networks:
  net:
  
# volumes:
#   sonarqube_conf:
#   sonarqube_data:
#   sonarqube_extensions:
#   sonarqube_bundled-plugins: