version: "3.8"
services:
  jenkins:
    container_name: jenkins
    build:
      context: ../lab05-jenkins-docker/jenkins
    image: jenkins/docker
    ports:
      - 8080:8080
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net   
  sonarqube:
      image: sonarqube:7.1
      container_name: sonarqube
      ports:
        - 8081:9000
      networks:
        - net
      ulimits:
        nofile:
          soft: 65536
          hard: 65536
      volumes:
        - $PWD/data/sonarqube/conf:/opt/sonarqube/conf
        - $PWD/data/sonarqube/data:/opt/sonarqube/data
        - $PWD/data/sonarqube/logs:/opt/sonarqube/logs
        - $PWD/data/sonarqube/extensions:/opt/sonarqube/extensions                    
networks:
  net:
  
