version: "3.8"
services:
  jenkins:
    container_name: jenkins
    build:
      context: ../lab05-jenkins-docker/jenkins
    image: jenkins/docker
    ports:
      - 8080:8080
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net   
  sonarqube:
      image: sonarqube:8.6.1-developer
      container_name: sonarqube
      ports:
        - 8081:9000
      networks:
        - net
      ulimits:
        nofile:
          soft: 65536
          hard: 65536
      environment:
        - sonar.jdbc.username=sonar
        - sonar.jdbc.password=sonar
        - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
      depends_on:
        - db
      volumes:
        - $PWD/data/sonarqube/conf:/opt/sonarqube/conf
        - $PWD/data/sonarqube/data:/opt/sonarqube/conf
        - $PWD/data/sonarqube/logs:/opt/sonarqube/logs
        - $PWD/data/sonarqube/extensions:/opt/sonarqube/extensions

  db:
    image: postgres
    networks:
      - net
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    # volumes:
    #   - postgresql:/var/lib/postgresql
    #   - postgresql_data:/var/lib/postgresql/data                      
networks:
  net:
  
